apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache-pvc
  namespace: github-actions-runner-octodemo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume: my-efs-volume
