apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-efs-volume
  labels:
    volume: my-efs-volume
spec:
  capacity:
    storage: 100Gi # Doesn't really matter, as EFS does not enforce it anyway
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - timeo=600
    - retrans=2
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /
    server: fs-3324334b.efs.us-east-2.amazonaws.com
